// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtqhlplkjabzkxtpucse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cWhscGxramFiemt4dHB1Y3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzcyMDksImV4cCI6MjA2NzIxMzIwOX0.TmuxJj1Qo_AWLQnCOcygCYbED1pXtla7qqqbaoM7lKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});